### ISSUE TITLE
[Question] Live Graph

### ISSUE THREAD

**Issue by bluekuen** [NdubuisiJr/skia-chart#18]
Hello together! 

First of all, great Plugin! I'm really glad i found it! 

Now to my Question: Is it possible to add Points at runtime?
I have a device which changes its speed and i want to show that over the time in a LineChart. 
Is it possible ? As i didn't found a way to do it yet but maybe i'm overseeing something. 

Greetings bluekuen

**Comment by NdubuisiJr** [comment]
Hi Bluekuen
Yes, you can add points at runtime.

All you have to do is bind the chart property of the `ChartCanvas` to a `LineChart` property in your view model. Then ensure you set the binding mode to `TwoWay`, and Raise the property changed event each time you add a point.

[Here is a YouTube tutorial](https://www.youtube.com/watch?v=YfEmzBfjG_o)
The example in the YouTube video was done with a BarChart and It is applicable to LineChart and the other supported Chart types.

Cheers!
