### ISSUE TITLE
[Enhancement] Zoom In Out and Scale X,Y funtionality 

### ISSUE THREAD

**Issue by WiproSarthak** [NdubuisiJr/skia-chart#28]
Line chart can have large data set.So user should be able to drag X,Y position and Zoom In Out to see all the data sets properly

**Comment by NdubuisiJr** [comment]
Hi @WiproSarthak 

Thanks for submitting this. We will look at implementing it as soon as we can.

Cheers.

**Comment by NdubuisiJr** [comment]
Hi @WiproSarthak 

Have you seen this [package](https://github.com/TBertuzzi/Xamarin.Forms.PinchZoomImage)?
Try wrapping the chart control around it and see if it solves you problem.

I'll be waiting for your feedback.
