### ISSUE TITLE
how to use via nuget?

### ISSUE THREAD

**Issue by mdmota** [NdubuisiJr/skia-chart#9]
I didn't understand how SkiaSharp works. Do I have to import the entire project?
I was unable to import the classes with the nuget library installed.
![error](https://user-images.githubusercontent.com/21266037/78291674-29cb6e80-74fc-11ea-89ae-56a2a8428f24.png)

**Comment by NdubuisiJr** [comment]
The Skia-Chart packages has not been released yet.... It's still under development stage.

**Comment by NdubuisiJr** [comment]
@mdmota we have just released a beta version of the chart library. You can now add it to your project using nuget. 
Thanks
